In [1]:
# install needed packages
!pip install rapidfuzz
!pip install pycountry

Requirement already satisfied: rapidfuzz in /opt/anaconda3/lib/python3.12/site-packages (3.5.2)
Collecting pycountry
  Downloading pycountry-24.6.1-py3-none-any.whl.metadata (12 kB)
Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 13.6 MB/s eta 0:00:00a 0:00:01
Installing collected packages: pycountry
Successfully installed pycountry-24.6.1

In [166]:
# import needed packages
import numpy as np
import pandas as pd
import pycountry
import rapidfuzz
import re
from rapidfuzz import process

# available shark species as reference
reference_species = ["African Angelshark","African Dwarf Sawshark","African Frilled Shark","African Lanternshark","African Ribbontail Catshark","African Sawtail Catshark","Angelshark (Monkfish)","Angular Angelshark","Angular Roughshark","Antilles Catshark","Arabian Carpetshark","Arabian Catshark","Arabian Smooth-hound","Argentine Angelshark","Arrow-head Dogfish","Atlantic Angelshark","Atlantic Sawtail Catshark","Atlantic Sharpnose Shark","Atlantic Weasel Shark","Australian Angelshark","Australian Blackspotted Catshark","Australian Blacktip Shark","Australian Grey Smooth-hound","Australian Marbled Catshark","Australian Reticulate Swellshark","Australian Sawtail Catshark","Australian Sharpnose Shark","Australian Spotted Catshark","Australian Swellshark","Australian Weasel Shark","Azores Dogfish","Bahamas Sawshark","Bali Catshark","Balloon Shark","Banded Houndshark","Banded Sand Catshark","Banded Wobbegong","Barbeled Houndshark","Barbelthroat Carpetshark","Bareskin Dogfish","Bartail Spurdog","Basking Shark","Beige Catshark","Bigeye Houndshark","Bigeye Sand Tiger","Bigeye Sixgill Shark","Bigeye Thresher Shark","Bighead Catshark","Bighead Spurdog","Bignose Shark","Birdbeak Dogfish","Black Dogfish","Black Roughscale Catshark","Black-tip sawtail catshark","Blackbelly Lanternshark","Blackgill Catshark","Blackmouth catshark","Blackmouth Lanternshark","Blacknose shark","Blackspot Shark","Blackspotted Catshark","Blackspotted Smooth-hound","Blacktail Reef Shark","Blacktailed Spurdog","Blacktip Reef Shark","Blacktip shark","Blacktip Tope","Blind Shark","Blotched Catshark","Blotchy Swellshark","Blue Shark","Bluegrey Carpetshark","Bluntnose Sixgill Shark","Blurred Lanternshark","Blurred Lanternshark","Boa Catshark","Boa Catshark","Bonnethead Shark","Borneo Catshark","Borneo Shark","Bramble Shark","Brazilian Sharpnose Shark","Bristled Lanternshark","Bristly Catshark","Broadbanded Lanternshark","Broadfin Sawtail Catshark","Broadfin Shark","Broadgill Catshark","Broadhead Catshark","Broadmouth Catshark","Broadnose Catshark","Broadnose Sevengill Shark","Broadsnout Lanternshark","Brown Catshark","Brown Shyshark","Brown Smooth-hound","Brownbanded Bamboo Shark","Brownspotted Catshark","Bull shark","Burmese Bamboo Shark","Campeche Catshark","Caribbean Lanternshark","Caribbean Reef Shark","Caribbean Roughshark","Caribbean Sharpnose Shark","Cenderawasih Epaulette Shark","Chain Catshark","Chilean Angelshark","Clouded Angelshark","Cloudy Catshark","Coates’ Shark","Cobbler Wobbegong","Collared Carpetshark","Combtooth Dogfish","Combtooth Lanternshark","Common Smooth-hound","Common Thresher Shark","Comoro Catshark","Cook’s Swellshark","Cookiecutter Shark","Copper Shark","Coral Catshark","Creek Whaler","Crescent Bullhead Shark","Crested Bullhead Shark","Crocodile Shark","Crying Izak","Cuban Dogfish","Cuban Ribbontail Catshark","Cylindrical Lanternshark","Cyrano Spurdog","Daggernose Shark","Dark Shyshark","Deepwater Catshark","Deepwater Sicklefin Houndshark","Densescale Lanternshark","Draughtsboard Shark","Dumb Gulper shark","Dusky Catshark","Dusky shark","Dusky Smooth-hound","Dwarf Catshark","Dwarf False Catshark","Dwarf Gulper Shark","Dwarf Lanternshark","Dwarf Sawfish","Dwarf Sawtail Catshark","Dwarf Smooth-hound","Dwarf Spotted Wobbegong","Eastern Angelshark","Eastern Banded Catshark","Eastern Highfin Spurdog","Eastern Longnose Spurdog","Eastern Spotted Gummy Shark","Edmund’s Spurdog","Elongate Carpetshark","Epaulette Shark","False Catshark","False Lanternshark","Fat Catshark","Fatspine Spurdog","Filetail Catshark","Finetooth Shark","Flaccid Catshark","Flagtail Swellshark","Flapnose Houndshark","Flat-head Catshark","Floral Banded Wobbegong","Freckled Catshark","Frilled Shark","Fringefin Lanternshark","Frog Shark","Galapagos Bullhead Shark","Galapagos Catshark","Galapagos Shark","Ganges Shark","Gecko Catshark","Ghost Catshark","Ginger Carpetshark","Goblin Shark","Graceful Catshark","Graceful Shark","Granular Dogfish","Granular Dogfish","Great Hammerhead Shark","Great Lanternshark","Great White Shark","Green Lanternshark","Green-eye Spurdog","Greenland Shark","Grey Bamboo Shark","Grey Sharpnose Shark","Grey Smooth-hound","Grinning Izak","Gulf Catshark","Gulf Smooth-hound","Gulper Shark","Gummy Shark","Hardnose Shark","Hardnose Shark","Harlequin Catshark","Hasselt’s Bamboo Shark","Hawailian Lanternshark","Hidden Angelshark","High-Fin Dogfish","Hoary Catshark","Honeycomb Izak Catshark","Hooded Carpet Shark","Hooktooth Dogfish","Hooktooth Shark","Horn Shark","Humpback Catshark","Humpback Smooth-hound","Iceland Catshark","Indian Swellshark","Indonesian Angelshark","Indonesian Greeneye Spurdog","Indonesian Shortsnout Spurdog","Indonesian Speckled Carpet Shark","Indonesian Speckled Catshark","Irrawady River Shark","Izak Catshark","Izu Catshark","Japanese Angelshark","Japanese Bullhead Shark","Japanese Catshark","Japanese Roughshark","Japanese Sawshark","Japanese Shortnose Spurdog","Japanese Spurdog","Japanese Topeshark","Japanese Velvet Dogfish","Japanese Wobbegong","Kermadec Spiny Dogfish","Kitefin Shark","Knife-tooth Dogfish","Lana’s Sawshark","Large-nose Catshark","Largespine Velvet Dogfish","Largetooth Cookiercutter Shark","Largetooth Sawfish","Leafscale Gulper Shark","Lemon Shark","Leopard Catshark","Leopard Epaulette Shark","Leopard Shark","Lesser-spotted Catshark","Lined Catshark","Lined Lanternshark (Etmopterus bullisi)","Lined Lanternshark (Etmopterus dislineatus)","Little Gulper Shark","Lizard Catshark","Llittle Sleeper Shark","Lollipop Catshark","Long-fin Catshark","Long-head Catshark","Long-nose Catshark","Long-nose Pygmy Shark","Long-nose Sawshark","Longcomb Sawfish","Longfin Catshark","Longfin Mako Shark","Longfin Sawtail Catshark","Longnose Houndshark","Longnose Sawtail Catshark","Longnose Spurdog","Longnose Velvet Dogfish","Longsnout Dogfish","Magnificent Catshark","Mandarin Dogfish","Mcmillan’s Catshark","Megamouth Shark","Mexican Horn Shark","Milk Shark","Moller’s Lanternshark","Mosaic Gulper Shark","Mouse Catshark","Mud Catshark","Narrow Sawfish","Narrow-fin Smooth-hound","Narrow-mouthed Catshark","Narrow-tail Catshark","Narrowbar Swellshark","Narrownose Smooth-hound","Natal Shyshark","Necklace Carpetshark","Nervous Shark","Network Wobbegong","New Caledonia Catshark","New Zealand Catshark","New Zealand Lanternshark","New Zealand Lanternshark","Night Shark","Northern River Shark","Northern Sawtail Catshark","Northern Spiny Dogfish","Northern Wobbegong","Nurse Shark","Nursehound Catshark","Oceanic Whitetip Shark","Ocellate Topeshark","Ocellated Angelshark","Oman Bullhead Shark","One-fin Catshark","Orange Spotted Catshark","Ornate Angelshark","Ornate Dogfish","Ornate Wobbegong","Pacific Angelshark","Pacific Nurse Shark","Pacific Sharpnose Shark","Pacific Sleeper Shark","Pacific Smalltail Shark","Pacific Spadenose Shark","Pacific Spiny Dogfish","Pale Catshark","Pale Spotted Catshark","Panama Ghost Catshark","Papuan Epaulette Shark","Pelagic Thresher Shark","Peppered Catshark","Phallic Catshark","Pigeye Shark","Pink Lanternashark","Pinocchio Catshark","Plunket Shark","Pocket shark","Pondicherry Shark","Porbeagle Shark","Port Jackson Shark","Portuguese Dogfish","Prickly Dogfish","Prickly Shark","Puffadder Shyshark","Pygmy Lanternshark","Pygmy Ribbontail Catshark","Pygmy Shark","Pyjama Catshark","Quagga Catshark","Rasptooth Dogfish","Redspotted Catshark","Reticulated Swellshark","Rough Longnose Dogfish","Rough-tail Catshark","Roughskin catshark","Roughskin Dogfish","Roughskin Spurdog","Rusty Carpetshark","Rusty Catshark","Saddle Carpetshark","Saddled Swellshark","Sail-back Houndshark","Sail-fin Roughshark","Salamander Catshark","Saldanha Catshark","Salmon Shark","Sand Tiger Shark","Sandbar Shark","Sarawak Pygmy Swellshark","Sawback Angelshark","Scalloped Bonnethead","Scalloped Hammerhead","School Shark","Scoop-head Hammerhead","Seychelles Gulper Shark","Seychelles Spurdog","Sharpfin Houndshark","Sharpnose Sevengill Shark","Sharptooth Houndshark","Sharptooth Lemon Shark","Sharptooth Smooth-hound","Sherwood’s Dogfish","Short-belly Catshark","Short-nose Spurdog","Short-tail Lanternshark","Short-tail Lanternshark","Short-tail Nurse shark","Shortfin Mako Shark","Shortnose Demon Catshark","Shortnose Sawshark","Shortspine Spurdog","Sicklefin Houndshark","Sicklefin Smooth-hound","Sicklefin Weasel Shark","Silky Shark","Silvertip shark","Six-gill Sawshark","Slender Bamboo Shark","Slender Catshark","Slender Sawtail Catshark","Slender Smooth-hound","Slender Weasel Shark","Slit-eye Shark","Small-belly Catshark","Small-dorsal Catshark","Small-eye Catshark","Small-eye Hammerhead","Small-eye Lanternshark","Small-eye Pygmy Shark","Small-eye Smooth-hound","Small-fin Catshark","Small-fin Gulper Shark","Smalltail Shark","Smalltooth Sand Tiger","Smalltooth Sawfish","Smooth Hammerhead","Smooth Lanternshark","Smooth-tooth Blacktip shark","Smoothback Angelshark","Snaggletooth Shark","Sombre Catshark","South China Catshark","Southern Lanternshark","Southern Mandarin Dogfish","Southern Sawtail Catshark","Southern Sleeper Shark","Spadenose Shark","Sparsetooth Dogfish","Speartooth Shark","Speckled Carpet Shark","Speckled Catshark","Speckled Smooth-hound","Speckled Swellshark","Spined Pygmy Shark","Spinner shark","Spiny Dogfish","Splendid Lanternshark","Sponge-head Catshark","Spot-tail Shark","Spotless Catshark","Spotless Smooth-hound","Spotted Estuary Smooth-hound","Spotted Houndshark","Spotted Wobbegong","Springer’s Sawtail Catshark","Starry Catshark","Starry Smooth-hound","Starspotted Smooth-hound","Stout Catshark","Straight-tooth weasel shark","Striped Smooth-hound","Swellshark","Tailspot Lanternshark","Taiwan Angelshark","Taiwan Saddled Carpetshark","Tall-light Shark","Tasselled Wobbegong","Tawny Nurse Shark","Thorny Lanternshark","Tiger Catshark","Tiger Shark","Triton Epaulette Shark","Tropical Sawshark","Variegated Catshark","Velvet Belly Lanternshark","Velvet Catshark","Velvet Dogfish","Viper Dogfish","West Indian Lanternshark","Western African catshark","Western Angelshark","Western Gulper Shark","Western Highfin Spurdog","Western Longnose Spurdog","Western Spotted Catshark","Western Wobbegong","Whale Shark","Whiskery Shark","White Ghost Catshark","White-bodied Catshark","White-clasper Catshark","White-fin Swellshark","White-margin Fin Houndshark","White-saddled Catshark","White-spotted Bamboo Shark","White-Spotted Catshark","White-spotted Smooth-hound","White-tail Dogfish","White-tip Catshark","White-tip Reef Shark","Whitecheek Shark","Whitefin Dogfish","Whitefin Topeshark","Whitenose Shark","Whitespotted Bullhead Shark","Whitetip Weasel Shark","Winghead Shark","Yellowspotted Catshark","Zebra Bullhead Shark","Zebra Shark"]

# url to shark attack file
url = "https://www.sharkattackfile.net/spreadsheets/GSAF5.xls"
df = pd.read_excel(url)

In [168]:
# Function to match and correct species
def correct_species(species, reference_list, threshold=80):
    corrected_species = ""
    corrected = process.extractOne(species, reference_list)  # Get the best match
    if corrected:  # Check if result is not None
        match, score, _ = corrected
        if score >= threshold:  # Only accept matches above the threshold
            corrected_species = match
        else:
            corrected_species = species  # No good match found
    else:
        corrected_species = species  # No match found at all
    return corrected_species

# Function to keep only allowed words in the string
def filter_string(input_string, allowed_words):
    # Create a regular expression pattern to match allowed words
    pattern = '|'.join(re.escape(word) for word in allowed_words)
    # Replace everything that is not in the allowed list with an empty string
    result = ' '.join(re.findall(pattern, input_string))
    return result

def country_check(country):
    return "Yes" if country in country_name else "No"

def invalid(Type): #define function
    if Type in ["Invalid", "Watercraft", "Sea Disaster", "Questionable", "Boat","?", "Unconfirmed", "Unverified", "Under investigation"]:
        return "Invalid"
    else:
        return Type

def convert_age(Age):
    try:
        # Handle specific categories
        if Age in ['60+', '60s', 'Elderly', "60's"]:
            return 65
        elif Age in ['Middle age', '50s', 'middle-age', '"middle-age"', '>50']:
            return 55
        elif Age in ['40s']:
            return 45
        elif Age in ['30s', 'mid-30s']:
            return 35
        elif Age in ['20s', "20's", 'mid-20s', '20/30', 'adult', '20?']:
            return 25
        elif Age in ['(adult)']:
            return 18
        elif Age in ['teen', 'Teen', 'Teens', 'a minor', 'young', '"young"']:
            return 15
        elif Age == 'Both 11':
            return 11
        elif Age == '6½':
            return 6
        elif Age == '2½':
            return 2
        elif Age in ['18 months', '9 months']:
            return 1

        # Handle ranges and multiple values
        elif isinstance(Age, str) and ('to' in Age or '&' in Age or 'or' in Age or ',' in Age):
            # Replace delimiters with spaces
            for symbol in ['to', '&', 'or', ',']:
                Age = Age.replace(symbol, ' ')
            # Extract numeric parts
            parts = Age.split()
            numbers = [float(part) for part in parts if part.isdigit()]
            if numbers:
                return numbers[0]  # Return the first number

        # Handle invalid entries
        elif Age in ['?', '!2', '!!', '!6', 'M', '45 and 15', '\xa0 ', 'Ca. 33',
                     'MAKE LINE GREEN', 'F', 'X', '  ', 'A.M.', '22, 57, 31', '28,']:
            return float('nan')

        # Handle any remaining strings
        elif isinstance(Age, str):
            Age = Age.strip()  # Remove leading/trailing whitespace
            if Age.isdigit():
                return float(Age)  # Convert valid numbers to float
            else:
                return float('nan')  # Return NaN for unrecognized strings

        # Return numeric values as-is
        else:
            return float(Age)
    except ValueError:
        return float('nan')  # Fallback for unexpected issues

In [170]:
# modify columns
df.columns = df.columns.map(lambda col: col.lower().strip())
df.columns = df.columns.map(lambda col: col.replace(" ", "_"))
df = df.rename(columns={"fatal_y/n": "fatal"})
df = df.drop_duplicates()
df = df.dropna(how='all')
df = df.drop(columns=['date', 'year', 'state', 'location', 'name', 'injury', 'time', 'source', 'pdf', 'href_formula', 'href', 'case_number', 'case_number.1', 'original_order', 'unnamed:_21','unnamed:_22'])
# unify fatality
df.fatal = df.fatal.apply(lambda x: str(x).lower().strip())
df.fatal = df.fatal.apply(lambda x: "y" if x=="yes" or x=="y" or x=="f" else "n" if x=="n" or x=="no" else "unknown")
# unify species with fuzzy
df['species'] = df['species'].apply(lambda x: correct_species(x, reference_species))
# only allow species names to be used
df['species'] = df['species'].apply(lambda x: filter_string(str(x), reference_species))

In [172]:
df.type.fillna("unknown")
df['type']=df['type'].apply(lambda x: invalid(x))
df['age'] = df['age'].apply(lambda x: convert_age(x))
df['type'] = df['type'].replace({' Provoked': 'Provoked'})
Sex_mapping = {'F': 'F', 'M': 'M', ' M':'M', 'M ':'M', 'M x 2':'Invalid', 'N':'Invalid', 'lli':'Invalid', '.':'Invalid'}
df['sex'] = df['sex'].map(Sex_mapping)

In [174]:
df["country"] = df["country"].apply(lambda x:x.upper() if isinstance(x,str) else x)
df["country"] = df["country"].apply(lambda x:x.strip() if isinstance(x,str) else x)
country_name = {country.name.upper() for country in pycountry.countries}
df["country"] = df["country"].apply(lambda x: 
                                                 "UNITED STATES" if x == "USA" else 
                                                 ("RÉUNION" if x == "REUNION" else 
                                                 ("IRAN, ISLAMIC REPUBLIC OF" if x == "IRAN" else
                                                 ("UNITED KINGDOM" if x == "ENGLAND" else
                                                 x))))

df["country"] = df["country"].apply(lambda x: 
                                                 "VIET NAM" if x == "VIETNAM" else 
                                                 ("RÉUNION" if x == "REUNION ISLAND" else 
                                                 ("RUSSIAN FEDERATION" if x == "RUSSIA" else
                                                 ("COLOMBIA" if x == "COLUMBIA" else
                                                 x))))

df["country"] = df["country"].apply(lambda x: 
                                                 "TÜRKIYE" if x == "TURKEY" else 
                                                 ("VENEZUELA, BOLIVARIAN REPUBLIC OF" if x == "VENEZUELA" else 
                                                 ("PAPUA NEW GUINEA" if x == "NEW GUINEA" else
                                                 ("TAIWAN, PROVINCE OF CHINA" if x == "TAIWAN" else
                                                 x))))

df["country"] = df["country"].apply(lambda x: 
                                                 "UNITED KINGDOM" if x == "SCOTLAND" else 
                                                 ("TANZANIA" if x == "TANZANIA" else 
                                                 ("JAPAN" if x == "OKINAWA" else
                                                 ("PORTUGAL" if x == "AZORES" else
                                                 x))))

df["country"] = df["country"].apply(lambda x: 
                                                 "TURKS AND CAICOS ISLANDS" if x == "TURKS & CAICOS" else 
                                                 ("MYANMAR" if x == "BURMA" else 
                                                 ("TRINIDAD AND TOBAGO" if x == "TRINIDAD & TOBAGO" else
                                                 ("CABO VERDE" if x == "CAPE VERDE" else
                                                 x))))

df["country"] = df["country"].apply(lambda x: 
                                                 "MALDIVES" if x == "MALDIVE ISLANDS" else 
                                                 ("SRI LANKA" if x == "CEYLON" else 
                                                 ("TRINIDAD AND TOBAGO" if x == "TOBAGO" else
                                                 ("SRI LANKA" if x == "CEYLON (SRI LANKA)" else
                                                 x))))

df["country"] = df["country"].apply(lambda x: 
                                                 "PAPUA NEW GUINEA" if x == "NEW BRITAIN" else 
                                                 ("MICRONESIA" if x == "MICRONESIA" else 
                                                 ("GREECE" if x == "CRETE" else
                                                 ("TURKS AND CAICOS ISLANDS" if x == "TURKS AND CAICOS" else
                                                 x))))
df['is_country'] = df["country"].apply(country_check)

In [176]:
df["activity"] = df["activity"].apply(lambda x:x.upper() if isinstance(x,str) else x)
df['new_activity'] = 'OTHER'
df.loc[df['activity'].str.contains('FELL', case=False, na=False), 'new_activity'] = 'FELL'

df.loc[df['activity'].str.contains('FILMING', case=False, na=False), 'new_activity'] = 'FILMING'

df.loc[df['activity'].str.contains(r'BATHING|WASHING|JUMP|WALK|STAND|SITT|PLAYING', case=False, na=False), 'new_activity'] = 'WASHING'

df.loc[df['activity'].str.contains(r'AIR', case=False, na=False), 'new_activity'] = 'RELATED TO AIRCRAFT'

df.loc[df['activity'].str.contains('FEED', case=False, na=False), 'new_activity'] = 'FEEDING ANIMALS'

df.loc[df['activity'].str.contains(r'PADDL|BOARDING', case=False, na=False), 'new_activity'] = 'PADDLE BOARDING'

df.loc[df['activity'].str.contains(r'BOAT|SHIP|YACHT|VESSEL|KAYAK|CANOE|ROW|BOARD|WRECK|ADRIF', case=False, na=False), 'new_activity'] = 'RELATED TO BOATS'

df.loc[df['activity'].str.contains('UNKNOWN', case=False, na=False), 'new_activity'] = 'UNKNOWN'

df.loc[df['activity'].str.contains('WAD', case=False, na=False), 'new_activity'] = 'WADING'

df.loc[df['activity'].str.contains('TOUCH', case=False, na=False), 'new_activity'] = 'TOUCHING SHARKS'

df.loc[df['activity'].str.contains('SURF', case=False, na=False), 'new_activity'] = 'SURFING'

df.loc[df['activity'].str.contains(r'SWIMMING|FLOATING', case=False, na=False), 'new_activity'] = 'SWIMMING'

df.loc[df['activity'].str.contains(r'DIVING|DAVE|DIVE', case=False, na=False), 'new_activity'] = 'DIVING'

df.loc[df['activity'].str.contains(r'FISH|CATCH|LOBST', case=False, na=False), 'new_activity'] = 'FISHING'
df['new_activity_1'] = np.where(df['new_activity'] == 'OTHER', df['activity'], df['new_activity'])

In [178]:
species_variety = df.groupby('country')['species'].nunique().reset_index()
species_variety = species_variety.sort_values(by="species", ascending=False)
species_variety

                                   country  species
189                          UNITED STATES       44
12                               AUSTRALIA       34
157                           SOUTH AFRICA       22
119                            NEW ZEALAND       13
13                                 BAHAMAS       12
188                         UNITED KINGDOM       12
21                                  BRAZIL       11
106                                 MEXICO       11
83                                   ITALY       11
163                                  SPAIN       10
56                        FRENCH POLYNESIA       10
86                                   JAPAN       10
48                                   EGYPT        8
118                          NEW CALEDONIA        8
54                                    FIJI        8
133                       PAPUA NEW GUINEA        8
132                                 PANAMA        8
145                                RÉUNION        8
113                             MOZAMBIQUE        7
19                                 BERMUDA        7
149                                SENEGAL        6
137                            PHILIPPINES        6
35                                COLOMBIA        6
28                                  CANADA        6
18                                  BELIZE        6
179                                  TONGA        6
40                                 CROATIA        5
130                                  PALAU        5
61                                  GREECE        5
77                               INDONESIA        5
41                                    CUBA        5
164                              SRI LANKA        5
74                                   INDIA        5
98                                MALAYSIA        5
174              TAIWAN, PROVINCE OF CHINA        5
160                            SOUTH KOREA        5
82                                  ISRAEL        4
177                               THAILAND        4
138                               PORTUGAL        4
50                             EL SALVADOR        4
85                                 JAMAICA        4
11                          ATLANTIC OCEAN        4
32                                   CHILE        4
183               TURKS AND CAICOS ISLANDS        4
97                              MADAGASCAR        4
150                             SEYCHELLES        4
101                       MARSHALL ISLANDS        4
39                              COSTA RICA        4
193                               VIET NAM        4
122                   NORTH ATLANTIC OCEAN        4
72                               HONG KONG        4
191                                VANUATU        4
107                             MICRONESIA        3
64                                    GUAM        3
129                          PACIFIC OCEAN        3
75                            INDIAN OCEAN        3
120                              NICARAGUA        3
71                                HONDURAS        3
55                                  FRANCE        3
144                     RUSSIAN FEDERATION        3
47                                 ECUADOR        3
90                                   KENYA        3
103                              MAURITIUS        3
79               IRAN, ISLAMIC REPUBLIC OF        3
33                                   CHINA        3
158                   SOUTH ATLANTIC OCEAN        3
27                              CABO VERDE        3
175                               TANZANIA        3
100                                  MALTA        3
99                                MALDIVES        3
3                           AMERICAN SAMOA        3
102                             MARTINIQUE        2
146                                  SAMOA        2
108                     MID ATLANTIC OCEAN        2
170                                  SUDAN        2
192      VENEZUELA, BOLIVARIAN REPUBLIC OF        2
190                                URUGUAY        2
186                   UNITED ARAB EMIRATES        2
185                                TÜRKIYE        2
182                                TUNISIA        2
181                    TRINIDAD AND TOBAGO        2
162                SOUTHWEST PACIFIC OCEAN        2
123                    NORTH PACIFIC OCEAN        2
156                                SOMALIA        2
154                        SOLOMON ISLANDS        2
151                           SIERRA LEONE        2
148                           SAUDI ARABIA        2
135                           PERSIAN GULF        2
127                                 NORWAY        2
95                                 LIBERIA        2
196                                  YEMEN        2
7                                  ANTIGUA        2
81                                 IRELAND        2
73                                 ICELAND        2
30                          CAYMAN ISLANDS        2
29                           CARIBBEAN SEA        2
88                         JOHNSTON ISLAND        2
8                                ARGENTINA        2
80                                    IRAQ        2
161                    SOUTH PACIFIC OCEAN        1
91                                KIRIBATI        1
31                         CENTRAL PACIFIC        1
26                     BRITISH WEST INDIES        1
25                  BRITISH VIRGIN ISLANDS        1
165  ST HELENA, BRITISH OVERSEAS TERRITORY        1
166                       ST KITTS / NEVIS        1
167                              ST MARTIN        1
168                            ST. MAARTIN        1
159                        SOUTH CHINA SEA        1
36                                 COMOROS        1
34                         COAST OF AFRICA        1
24              BRITISH OVERSEAS TERRITORY        1
155              SOLOMON ISLANDS / VANUATU        1
37                            COOK ISLANDS        1
153                               SLOVENIA        1
152                              SINGAPORE        1
38                               CORAL SEA        1
42                                 CURACAO        1
43                                  CYPRUS        1
44                            DIEGO GARCIA        1
169                             ST. MARTIN        1
23                      BRITISH NEW GUINEA        1
171                                 SUDAN?        1
172                                 SWEDEN        1
195                          WESTERN SAMOA        1
194                            WEST INDIES        1
2                                  ALGERIA        1
4               ANDAMAN / NICOBAR ISLANDAS        1
5                          ANDAMAN ISLANDS        1
6                                   ANGOLA        1
187             UNITED ARAB EMIRATES (UAE)        1
9                                    ARUBA        1
10                                   ASIA?        1
184                                 TUVALU        1
14                                 BAHREIN        1
15                              BANGLADESH        1
16                                BARBADOS        1
180                               TRINIDAD        1
17                           BAY OF BENGAL        1
178                            THE BALKANS        1
20                BETWEEN PORTUGAL & INDIA        1
176                             TASMAN SEA        1
22                           BRITISH ISLES        1
45                                DJIBOUTI        1
173                                  SYRIA        1
147                            SAN DOMINGO        1
49                          EGYPT / ISRAEL        1
46                      DOMINICAN REPUBLIC        1
70                                  HAWAII        1
68                                  GUYANA        1
117                                  NEVIS        1
116                   NETHERLANDS ANTILLES        1
115                                NAMIBIA        1
114                                MYANMAR        1
69                                   HAITI        1
112                                MOROCCO        1
111                             MONTENEGRO        1
110                                 MONACO        1
109                       MID-PACIFC OCEAN        1
76                           INDIAN OCEAN?        1
92                                   KOREA        1
105                      MEDITERRANEAN SEA        1
104                                MAYOTTE        1
78                             IRAN / IRAQ        1
84                         ITALY / CROATIA        1
87                                    JAVA        1
1                                   AFRICA        1
96                                   LIBYA        1
89                                  JORDAN        1
94                                 LEBANON        1
93                                  KUWAIT        1
67                            GULF OF ADEN        1
66                                  GUINEA        1
121                                NIGERIA        1
65                               GUATEMALA        1
143                                 ROATAN        1
142                               RED SEA?        1
141                 RED SEA / INDIAN OCEAN        1
140                                RED SEA        1
139                            PUERTO RICO        1
51            EQUATORIAL GUINEA / CAMEROON        1
52                        FALKLAND ISLANDS        1
136                                   PERU        1
53          FEDERATED STATES OF MICRONESIA        1
134                               PARAGUAY        1
57                                   GABON        1
58                                 GEORGIA        1
131                PALESTINIAN TERRITORIES        1
59                                   GHANA        1
60                            GRAND CAYMAN        1
128                                  OCEAN        1
62                               GREENLAND        1
126               NORTHERN MARIANA ISLANDS        1
125                   NORTHERN ARABIAN SEA        1
124                              NORTH SEA        1
63                                 GRENADA        1
0                        ADMIRALTY ISLANDS        1